.\" 
.\"    BskyId  Copyright (C) 2024  Aptivi
.\" 
.\"    BskyId is free software: you can redistribute it and/or modify
.\"    it under the terms of the GNU General Public License as published by
.\"    the Free Software Foundation, either version 3 of the License, or
.\"    (at your option) any later version.
.\"
.\"    BskyId is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    GNU General Public License for more details.
.\"
.\"    You should have received a copy of the GNU General Public License
.\"    along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\"

.TH bskyid 1 "6 Jun 2025" "1.0.2" "BskyId"
.SH NAME
BskyId \- Gets your BlueSky ID from your handle
.SH SYNOPSIS
bskyid <handle> [-plain/-nocolor]
.SH DESCRIPTION
BskyID is a simple shell script that returns just a BlueSky ID associated with your BlueSky account. This ID is a unique identifier for your BlueSky account and can't be edited.
.SH DOCUMENTATION
The whole documentation can be found in https://aptivi.gitbook.io/aptivi/bskyid-manual.
.SH AUTHOR
Aptivi (ceo AT aptivi DOT anonaddy DOT com)
