name: Build Project (Debian Package)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo apt update
          sudo NEEDRESTART_SUSPEND=1 apt install devscripts debhelper-compat dput build-essential
        
      - name: Make original package
        run: |
          mv debian ..
          mv .github ..
          tar cfv ../bskyid_1.0.1.orig.tar .
          xz ../bskyid_1.0.1.orig.tar
          mv ../debian .

      - name: Build package
        run: |
          debuild --no-lintian -us -uc
          cp ../*.deb .
        
      - name: Upload package to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Debian-Package
          path: "*.deb"
